### ISSUE TITLE
Doubt in adding number of questions

### ISSUE THREAD

**Issue by niharika06** [Promact/trappist#11]
#It is clearly written in the requirement that the user cannot add number of questions more than the provided number of question at the time of test creation. Can user add less than the provided number of questions?

**Comment by ShagunParikh** [comment]
**Update in Requirement** - We have **Eliminated** the functionality "To set the number of questions at the time of test creation". Hence, now a user can add any number of questions in the test. There will be no pre-defined upper limit set during the test creation process.
