### ISSUE TITLE
Message for deleted test if the user can not delete the test.

### ISSUE THREAD

**Issue by ritika05** [Promact/trappist#193]
In case of delete test If there is even one test Attendee the test should not be deleted.. So where should I display the message that the selected test can not be deleted. in the dialog which is opened or in the snack bar?
Assumption: When the user clicks on the delete option then, if the user can not delete the test a dialog will open showing the message that the selected test can not be deleted and if the user can delete the test then the delete confirmation dialog will open.
Is my assumption correct?

**Comment by iroshni** [comment]
You are correct.
