### ISSUE TITLE
Maximum number of options for Single/Multiple answer Question type

### ISSUE THREAD

**Issue by Sandipan-Ghosh** [Promact/trappist#199]
Is there any upper limit of the number of options that an user can add for any particular question of single/multiple answer question type?

**Comment by iroshni** [comment]
Please write proper description of you issue.

**Comment by iroshni** [comment]
Yes, we can keep maximum 10 options. Once the user has added 10 options, Add Options button will be hidden and a message will be shown that maximum 10 options can be added. Please coordinate with @viharsanghavi and @Krunal-Promact  on this.
