### ISSUE TITLE
Number of options related issue

### ISSUE THREAD

**Issue by viharsanghavi** [Promact/trappist#2]
Question:
The system provides four radio button/checkbox by default. If the test conductor wants to add questions which have less than four options like a true / false question then he/she can able to do it or not. If he/she can do it, then what about extra options.

**Comment by Krunal-Promact** [comment]
By default, there will be four options available to write an answer. But in case there are less than four options exist four any Question, a user will write only possible answers and leave rest of the checkbox/radio button blank. so if there are only 2 answers to any question, a user will write 2 answers and leave 2 answers as blank. so only 2 answers will be considered. And at least 2 answers should be required for any Checkbox or Radio Button type question.
