### ISSUE TITLE
Reports  - Design vs Requirement conflicts.

### ISSUE THREAD

**Issue by ShagunParikh** [Promact/trappist#200]
### Multiple Students Test Reports:

**Q1.**
As mentioned in wiki https://redmine.promactinfo.com/projects/online-quiz/wiki/A_Filter_Area, The Multiple student test reports listing area should have the following filters - Completed Tests, Expired test, Blocked Candidate, Overall score & Overall Percentage.

But there are no such filters present in the png designed for the Trappist placed at \\server12\Trainees\Designs\ViewTestReport.png.

Hence please specify if we should keep these filters or not?

**Q2.**
There is a functionality called "starred candidates" where the user can star/unstar the candidate in Multiple students reports list. And later, the user can filter out the starred candidates from the list when required. In png designed for the Trappist placed at \\server12\Trainees\Designs\ViewTestReport.png, there is an option to star/unstar the candidates in the list. Bt option to filter these starred candidates is missing from the png.

### Single Student Test Report:

**Q3**
 In png designed for the Trappist placed at \\server12\Trainees\Designs\ViewIndividualReport.png, the "Percentile of the Candidate" is displayed. Now, The percentile is a comparison score. It gives an idea of how good/bad a candidate did as compared to other candidates. Hence it is relative to the number of candidates who has given the test. Hence i suggest that we should show the **number of candidates that have given the test** along with the percentile.

**Comment by iroshni** [comment]
As discussed, we have candidates filtering based on the criteria mentioned in the wiki. As of now, we will not include range filters. And starred candidate will be one of the options with Candidate type filtering.

**Comment by iroshni** [comment]
for Q3, Lets incorporate your suggestion "we should show the number of candidates that have given the test along with the percentile".

**Comment by iroshni** [comment]
for Q1, latest designs are available in folder.
