### ISSUE TITLE
Test Question Selection page

### ISSUE THREAD

**Issue by asif-khan17** [Promact/trappist#202]
we are supposing that The Test name , Edit button and preview button will be bound throughout the test page? is our assumption right?

**Comment by iroshni** [comment]
I didn't get your question. Please elaborate in detail.

**Comment by asif-khan17** [comment]
I wanted to ask that at test  question selection page my assumptions are..
1.I m supposing that Test Name with edit icon will also be bound there.
2.I need to display the test name above and edit test name also.
3.I need to redirect to the preview page by clicking the preview button.
our assumptions are correct..?

**Comment by DhrutiShah** [comment]
What is the assumption in it? it was already there in Designs.

There are list of Pages in Test Module. Once Test is created Successfully all the pages have Test Name, Edit button and Preview button in top of the window. so it should be taken in basic template for all the other . not is each of the Pages. Integration should not be done in all the pages. and it is already done in test settings page. 

though preview button will be there in each pages, but unless and  until 1 Question is not added in the test, it will open **pop up** message that "Please Add At least one Question For Preview of the Test". if question is there it will be redirected to Preview page.
