### ISSUE TITLE
Validations for Correct and Incorrect Marks fields of Test Settings page 

### ISSUE THREAD

**Issue by Madhurima94** [Promact/trappist#244]
Correct Marks and Incorrect Marks fields of Test Settings Page can contain decimal values. Number of digits that should be allowed  before and after decimal  is not mentioned in the validation. Again, whether the value of Incorrect Marks Field should be lesser or not from the value of the Correct Marks Field is not mentioned in the validation. And also the maximum limit of correct marks is not defined.

**Comment by ShagunParikh** [comment]
1. Max number of digits after decimal point - **2**
2. Max number of digits before decimal point - **4**
3. The value of Incorrect Marks Field should be lesser or not from the value of the Correct Marks Field - **No, It's not mandatory**.
4. Maximum limit of Correct/Incorrect marks - **4 digit number**.
