### ISSUE TITLE
Validation for Test Duration field of Test Settings Page

### ISSUE THREAD

**Issue by Madhurima94** [Promact/trappist#250]
It is mentioned in the requirement that the user should be able to define a Max Time limit of the Test in minutes for the Test Duration field of the Test Settings Page. But what should be the maximum limit of the Test Duration field is not mentioned in the validation. Also, the validation that the value of the Test Duration field should be greater than the value of the Warning Time field is not mentioned under the Validations part of the Test Duration field.

**Comment by ShagunParikh** [comment]
1.  The validation that the value of the Test Duration field should be greater than the value of the Warning Time field is not mentioned under the Validations part of the Test Duration field - **It is mentioned here https://redmine.promactinfo.com/projects/online-quiz/wiki/Test-settings_ under Set Warning Message & Time > _Validations - The warning time should accept only integer values. The value should be less than Test duration_.** 

2. What should be the maximum limit of the Test Duration field is not mentioned in the validation - **Need to discussed with @iroshni.**

**Comment by Madhurima94** [comment]
But I had a discussion with the Tester and according to her there should be a separate error message if the value entered in the test duration field is lesser than or equal to the warning time field.

**Comment by Madhurima94** [comment]
The error message that the waning time should be lesser than the test duration time will be shown for the warning time field. And on entering negative value or non-integer values, an error message should be shown for the test duration field.

**Comment by ShagunParikh** [comment]
What should be the maximum limit of the Test Duration field is not mentioned in the validation - **24 Hours(In minutes).**

**Comment by ShagunParikh** [comment]
Update:  Maximum limit of the Test Duration - **Max 4 digit number.**
