### ISSUE TITLE
Functionality of Test Launch Dialog Box

### ISSUE THREAD

**Issue by Madhurima94** [Promact/trappist#279]
According to the requirement, there will be a button Save & Share in the footer of Test Settings Page. On clicking the button a dialog box should appear containing a text box and two buttons - Copy and Close.
On clicking the Copy button the Link of the Test should get copied. But how will the Test Attendees get access to the Test Link? Will the Test Link be provided to the Test Attendees after the Test Registration?

**Comment by ShagunParikh** [comment]
On clicking the Copy button the Link of the Test should get copied. This copied link will be sent to Attendees via email(manually). 

_Will the Test Link be provided to the Test Attendees after the Test Registration?_ - No, the Test Registration Page will be displayed when the Attendees click on the link sent to them in the email.
