### ISSUE TITLE
Issue in Sending mail to server

### ISSUE THREAD

**Issue by patelhr** [Promact/trappist#34]
I need proper valid credential & server name for sending mail because using my promact credential and promact server name, server is not responding so provide me email credential and server name for sending mail.

**Comment by iroshni** [comment]
you can try if you have any other email account then promact.

**Comment by patelhr** [comment]
ma'am If I try with gmail it say smtp server not support authentication.I think I don't have an access of gmail account.

**Comment by iroshni** [comment]
with Gmail you will have another SMTP server. which you can search on net. promact's SMTP server cant send mail of gmail account.

**Comment by patelhr** [comment]
ma'am I provided "smtp.gmail.com"  SMTP server ,Port:587 but still same error
