### ISSUE TITLE
Who will create the questions and categories????

### ISSUE THREAD

**Issue by asif-khan17** [Promact/trappist#346]
I m assuming that there is an admin who will create the categories and questions to provide the users of trappist so that no any user needs to create categories and questions by themselves and it will be available to all who wants to use trappist..
m I correct ...?
Or every user will create his own categories and questions..?

**Comment by Krunal-Promact** [comment]
What exactly is the issue that you are facing? There is no admin concept in Trappist.

**Comment by asif-khan17** [comment]
then who will create the questions and categories..?
