### ISSUE TITLE
Updation in Requirement

### ISSUE THREAD

**Issue by viharsanghavi** [Promact/trappist#37]
Old:
Question Details: Here a User will add Question. A Question should be added through rich text editor with bold, italic, underline, font size and code formatting options. Here by default, there will be one textbox (that textbox is rich text editor) to add a Question.

Update:
Question Details: Here a User will add Question. A Question should be added through textbox. Here by default, there will be one textbox to add a Question.

Can i update in Redmine?

**Comment by Krunal-Promact** [comment]
perfect. please approve it in Redmine wiki.
