### ISSUE TITLE
Validation of Connection String

### ISSUE THREAD

**Issue by patelhr** [Promact/trappist#5]
In original specification connection string validation is required.So here I assume that I need to validate connection string is connect to database or not?  If not connect to database than prompted error with enter correct connection string.
Please confirm my assumption is correct or incorrect?

**Comment by iroshni** [comment]
Your sentence is not in proper English, So what I assume that you are trying to convey is, you need to validate connection string by connecting database with it. If the connection is successful, it is valid, else not.
If my assumption is right then, you have understood correct.
