### ISSUE TITLE
Issue In BasicSetup application class

### ISSUE THREAD

**Issue by patelhr** [Promact/trappist#54]
In ApplicationClasses folder
If we created BasicSetup.cs model with  ConnectionStringParameter class object than every time we have to give user credential otherwise it will throw exception because in BasicSetup.cs class we mentioned user credential field required so it will create problem.

**Comment by iroshni** [comment]
Which exception it is throwing and when?

**Comment by patelhr** [comment]
When I provide connection string from postman in ModelState it is Invalid and give {Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary.KeyEnumerable} false.

**Comment by iroshni** [comment]
So does it throw exception ?

**Comment by patelhr** [comment]
No it show only false connection string.

**Comment by iroshni** [comment]
So why you wrote in your issue that it throws the exception? Please be specific with what you ask with proper words. 

That is the reason I asked you to send string parameter containing connection string and not the whole model.

**Comment by patelhr** [comment]
okk.So I have to give individual parameter for connection string.
