### ISSUE TITLE
Need title for code snippet question

### ISSUE THREAD

**Issue by Deepankar-promact** [Promact/trappist#56]
There is a need for title in the coding question which will briefly describe the question. Coding Questions are usually larger and more formatted than any other type of question. Displaying coding question on dashboard can consume lot of screen space and only few question can be displayed on one page.

**Comment by Krunal-Promact** [comment]
how title will be effective in this case. please elaborate.

**Comment by Deepankar-promact** [comment]
Titles are brief and will consume less screen space. Coding questions usually have minimum of three sections :- Question Details, Input, Output (May also contain input constrains).  
For Example:
(Question Details)
Reverse a given array.
(Input)
N - length of array
A1 A2 A3 - space separated elements of array
(Output)
 An An-1 ... A1 - reverse array
The above question will consume lots of screen space in the dashboard. We can give a title for the above question, say 'Reverse Array', and display only the title on the dashboard.

**Comment by Krunal-Promact** [comment]
as of now, we are only showing question detail on screen. no input and output values will be shown.

**Comment by Deepankar-promact** [comment]
Ok
