### ISSUE TITLE
Assumption: In Creating a new test

### ISSUE THREAD

**Issue by niharika06** [Promact/trappist#6]
I assume that after creating and submitting a new test, giving the name and number of questions,  it will be redirected to the dashboard.
Am I right or wrong?

**Comment by iroshni** [comment]
Test creation process is a stepwise process. It is not necessary to create the whole test at one go. So anytime in between, he can navigate to other pages. Last saved changes for the test will be available on subsequent edits. And to answer your question, Yes he will be redirected to test dashboard on successful creation of a test.

**Comment by niharika06** [comment]
Will there be any such option like save changes?

**Comment by iroshni** [comment]
Stepwise process refers to saving the changes at intermediate stages. So at each stage, you will have the option to save the changes. At the time of test creation, Adding questions to the test and while filling up the test settings.
