### ISSUE TITLE
Issues on validating Email Settings

### ISSUE THREAD

**Issue by patelhr** [Promact/trappist#8]
In original specification specified that we have to verify email settings are correct or not?
I don't get this details.
Does I have to implement SMTP server module and validate details or I need to give just one static example 
e.g:Server name:gmail,   Port:475,  Username: patelhrp7@gmail.com, password:1234 and validate from this example ?

**Comment by iroshni** [comment]
Please learn how emails are sent. What is the point in verifying static data?. You have to verify Email sending details entered by the user.

**Comment by patelhr** [comment]
So I have to implement SMTP server module to verify email settings or I just need to check normal validation?

**Comment by iroshni** [comment]
What is SMTP server module ?

**Comment by patelhr** [comment]
Mail kit module to configure smtp in our application

**Comment by iroshni** [comment]
.Net have inbuilt libraries to send emails. So you have to use them.

**Comment by patelhr** [comment]
Okk.So I am responsible person to implement functionality to send an email.
