### ISSUE TITLE
Email id field doubt 

### ISSUE THREAD

**Issue by spartha1995** [Promact/trappist#9]
Question : In Filter Area of multiple student Report a user can search by name or Email id. But there are no Email id field mentioned for sorting.
Assumption : We have to create a Email id field for Sorting like name
Let me know my assumption is Correct or not.

**Comment by ShagunParikh** [comment]
> In Filter Area of multiple student Report a user can search by name or Email id

This requirement states that there will a Search-Box, where the user can search for any student by entering his/her Name or Email Id. It has nothing to do with the sorting of the list of the students.

As mentioned in Multiple Students Report [2.1.2] - _The list of students is to be **sortable** by **Name**, **Test Date** and **Score** with the Score in descending order being the default_.
